name: Check for Changelog Update

on:
  pull_request:
    branches:
      - master

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch base branches
        run: git fetch origin master

      - name: Check for [no-changelog] in last commit
        id: check_commit
        run: |
          if git log -1 --pretty=%B | grep -q '\[no-changelog\]'; then
            echo "skip=true" >> $GITHUB_OUTPUT  
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Check if CHANGELOG.md was updated
        if: steps.check_commit.outputs.skip == 'false'
        run: |
          if git diff --name-only origin/master...HEAD | grep -q '^CHANGELOG.md$'; then
            echo "CHANGELOG.md updated."
          else
            echo "CHANGELOG.md not updated. Please add a changelog entry"
            exit 1
          fi 