name: Check for Changelog Update

on:
  pull_request:
    branches: [develop]

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine if PR authored by release-please bot
        id: release_please
        run: |
          set -euo pipefail
          TITLE="${{ github.event.pull_request.title }}"
          if [ "${{ github.event.pull_request.user.login }}" = "github-actions[bot]" ] && \
             printf '%s' "$TITLE" | grep -q '^chore(develop): release'; then
            echo "skip=true" >>"$GITHUB_OUTPUT"
          else
            echo "skip=false" >>"$GITHUB_OUTPUT"
          fi

      - name: Enforce release-please managed changelog
        if: steps.release_please.outputs.skip == 'false'
        run: |
          set -euo pipefail
          git fetch origin ${{ github.event.pull_request.base.ref }}
          if git diff --name-only origin/${{ github.event.pull_request.base.ref }}...HEAD | grep -q '^CHANGELOG.md$'; then
            echo "Please remove manual changes to CHANGELOG.md. The changelog is managed automatically by release-please." >&2
            exit 1
          fi
          if git ls-tree -r origin/${{ github.event.pull_request.base.ref }} --name-only | grep -q '^\.release-please-manifest.json$'; then
            if git diff --name-only origin/${{ github.event.pull_request.base.ref }}...HEAD | grep -q '^\.release-please-manifest.json$'; then
              echo "Please do not edit .release-please-manifest.json directly." >&2
              exit 1
            fi
          fi
          if git ls-tree -r origin/${{ github.event.pull_request.base.ref }} --name-only | grep -q '^VERSION$'; then
            if git diff --name-only origin/${{ github.event.pull_request.base.ref }}...HEAD | grep -q '^VERSION$'; then
              echo "Please do not bump VERSION manually. release-please controls the version." >&2
              exit 1
            fi
          fi
