name: Release Please

on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Run release-please
        uses: google-github-actions/release-please-action@v4
        with:
          command: manifest
          default-branch: develop
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
