name: Publish Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  verify_tag:
    name: Verify tag source
    runs-on: ubuntu-latest
    outputs:
      allowed: ${{ steps.decision.outputs.allowed }}
      reason: ${{ steps.decision.outputs.reason }}
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Evaluate tag
        id: decision
        run: |
          set -euo pipefail
          if [[ "${GITHUB_REF_NAME}" == *"-rc"* ]]; then
            echo "Release candidate tag detected; final release workflow will not run." >&2
            echo "allowed=false" >> "$GITHUB_OUTPUT"
            echo "reason=Release candidate tag - handled by prerelease workflow" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          branches=$(git branch -r --contains "$GITHUB_SHA" | sed 's/^ *//')
          echo "Branches containing commit:\n$branches"
          if echo "$branches" | grep -E '^origin/master$' >/dev/null; then
            echo "allowed=true" >> "$GITHUB_OUTPUT"
            echo "reason=Tag is on master" >> "$GITHUB_OUTPUT"
            echo "Tag verified on master. Proceeding with release." >&2
          else
            echo "Tag is not on master; skipping publish." >&2
            echo "allowed=false" >> "$GITHUB_OUTPUT"
            echo "reason=Tag is not on master" >> "$GITHUB_OUTPUT"
          fi

  build:
    name: Build and test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    needs: verify_tag
    if: needs.verify_tag.outputs.allowed == 'true'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    env:
      BLOCH_VERSION: ${{ github.ref_name }}

    steps:
      - name: Checkout (with tags)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure CMake (Release)
        if: runner.os != 'Windows'
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Run unit tests
        run: ctest --test-dir build -C Release --output-on-failure

      - name: Package artifact
        if: runner.os != 'Windows'
        shell: bash
        env:
          TAG_NAME: ${{ github.ref_name }}
        run: |
          set -euo pipefail
          mkdir -p dist
          BIN="build/bin/bloch"
          if [ ! -f "$BIN" ]; then
            [ -f "build/bloch" ] && BIN="build/bloch" || true
            [ -f "build/Release/bloch" ] && BIN="build/Release/bloch" || true
          fi
          if [ ! -f "$BIN" ]; then
            echo "Could not find built binary at $BIN" >&2
            ls -R build || true
            exit 1
          fi
          ASSET="bloch-${TAG_NAME}-${RUNNER_OS}-${RUNNER_ARCH}.tar.gz"
          cp "$BIN" dist/bloch
          cp LICENSE dist/ 2>/dev/null || true
          if [ -f scripts/install.sh ]; then cp scripts/install.sh dist/install.sh; fi
          if [ -f dist/install.sh ]; then
            chmod +x dist/install.sh || true
            tar -C dist -czf "$ASSET" bloch LICENSE install.sh 2>/dev/null || tar -C dist -czf "$ASSET" bloch LICENSE
          else
            tar -C dist -czf "$ASSET" bloch LICENSE 2>/dev/null || tar -C dist -czf "$ASSET" bloch
          fi
          echo "Packaged $ASSET"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: bloch-${{ github.ref_name }}-${{ runner.os }}-${{ runner.arch }}
          path: |
            *.tar.gz
            *.zip
          if-no-files-found: error

  release:
    name: Publish GitHub Release
    runs-on: ubuntu-latest
    needs: build
    if: needs.verify_tag.outputs.allowed == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: List artifacts
        run: ls -R dist

      - name: Generate checksums
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          files=(dist/*.tar.gz dist/*.zip)
          if [ ${#files[@]} -eq 0 ]; then
            echo "No artifacts found to checksum" >&2
            exit 1
          fi
          if command -v sha256sum >/dev/null 2>&1; then
            (cd dist && sha256sum *.tar.gz *.zip > checksums.txt 2>/dev/null || sha256sum *.tar.gz > checksums.txt)
          else
            (cd dist && shasum -a 256 *.tar.gz *.zip > checksums.txt 2>/dev/null || shasum -a 256 *.tar.gz > checksums.txt)
          fi
          echo "Generated dist/checksums.txt"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Bloch ${{ github.ref_name }}
          prerelease: false
          generate_release_notes: true
          files: |
            dist/**.tar.gz
            dist/**.zip
            dist/checksums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
