name: Tag Release

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect VERSION change
        id: detect
        run: |
          set -euo pipefail
          VERSION=$(cat VERSION | tr -d ' \n')
          if [ -z "$VERSION" ]; then
            echo "VERSION file is empty" >&2
            exit 1
          fi
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

          if git rev-parse HEAD^ >/dev/null 2>&1; then
            if git diff --name-only HEAD^ HEAD | grep -q '^VERSION$'; then
              echo "changed=true" >> "$GITHUB_OUTPUT"
            else
              echo "changed=false" >> "$GITHUB_OUTPUT"
            fi
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Create release tag
        if: steps.detect.outputs.changed == 'true'
        env:
          VERSION: ${{ steps.detect.outputs.version }}
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          tag="v${VERSION}"
          git fetch --tags origin
          if git show-ref --tags --quiet "$tag"; then
            echo "Tag $tag already exists. Nothing to do."
            exit 0
          fi

          git tag -a "$tag" -m "Bloch ${VERSION}"
          git push origin "$tag"

          echo "Created $tag"
